name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang, msvc]
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: macos-latest
            compiler: msvc

    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v2

      - name: Run the tests
        run: ./command/test.sh

      - name: Run the examples
        run: |
          ./command/example.sh lamping-example
          # The palindrome example is interactive.

  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Reserve huge pages
        run: sudo sysctl vm.nr_hugepages=4096

      - name: Run the benchmarks
        run: ./command/bench.sh
